CREATE DATABASE tessera;

USE tessera;

CREATE TABLE IF NOT EXISTS tx (
  txhash CHAR(66) NOT NULL PRIMARY KEY,
  blocknum BIGINT NOT NULL,
  fromaccount CHAR(42) NOT NULL,
  toaccount CHAR(42),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS request (
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  apiKey CHAR(42) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX apikey_index ON request(apiKey)